version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  logfile:
    formatter: default
    class: logging.FileHandler
    filename: logs//current.log
  stdout:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  root:
    level: INFO
    handlers:
      - logfile
      - stdout
    propagate: no